name: Dependency Security Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "My Secure App"
          scanPath: "."
          format: "HTML"
          out: "reports"

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: dep-check-report
          path: reports/
