name: Docker & Terraform Security Scan with SARIF # Trivy + Checkov

on:
  push:
    paths:
      - '**/Dockerfile'
      - '**/*.tf'
  pull_request:
    paths:
      - '**/Dockerfile'
      - '**/*.tf'

permissions:
  contents: read
  security-events: write  # Required for SARIF upload

jobs:
  docker-terraform-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # -------------------------------
      # TRIVY (Filesystem Vulnerabilities)
      # -------------------------------
      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install trivy -y

      - name: Trivy Filesystem Scan (SARIF)
        run: trivy fs --format sarif --output trivy-results.sarif .

      - name: Upload SARIF Report (Trivy)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif

      # -------------------------------
      # CHECKOV (Terraform Security)
      # -------------------------------
      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on Terraform (SARIF)
        run: checkov -d . --output sarif --output-file-path checkov-results.sarif

      - name: Upload SARIF Report (Checkov)
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: checkov-results.sarif
